server:
  port: 9001
#注册给注册中心  取名
spring:
  application:
    name: order-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SGQ
        metadata: v1

#  datasource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/homework?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
#      username: root
#      password: 123456

##mybatis-plus
#mybatis-plus:
#    mapper-locations: classpath:/mapper/*.xml
#    typeAliasesPackage: com.softeem.pojo
