server:
  port: 55557
spring:
  application:
    name: provide-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849


logging:
  level:
    root: info
    org.springframework: info

